export function run({ module, inputs }) {
  const result = module.renderText(String(inputs.text), {
    font: inputs.font,
    style: {
      gradient: ['#22c55e', '#06b6d4', '#6366f1'],
      gradientDirection: 'diagonal',
    },
    defaultFormat: 'plain',
  })
  const serialized = result.toJSON()

  return {
    plain: result.toPlainText().split('\n'),
    ansi: result.toANSI({ colorLevel: 3 }),
    html: result.toHTML({
      ariaLabel: String(inputs.text),
      includeContainer: true,
      containerClassName: 'sumi-example',
    }),
    svg: result.toSVG({
      title: 'SumiJS example',
      description: 'ASCII art generated by SumiJS',
      background: 'transparent',
    }),
    jsonSummary: {
      version: serialized.version,
      width: serialized.width,
      height: serialized.height,
      source: serialized.metadata.source,
      font: serialized.metadata.font,
    },
  }
}
