export function run({ module, inputs }) {
  const text = String(inputs.text)
  const result = module.renderText(text, {
    font: inputs.font,
    style: {
      gradient: ['#22c55e', '#06b6d4', '#6366f1'],
      gradientDirection: 'diagonal',
    },
    defaultFormat: 'plain',
  })
  const serialized = result.toJSON()

  return {
    html: result.toHTML({
      ariaLabel: text,
      includeContainer: true,
      containerClassName: 'sumi-example',
      inlineStyles: true,
    }),
    plain: result.toPlainText().split('\n'),
    ansi: result.toANSI({ colorLevel: 3 }),
    svg: result.toSVG({
      title: 'SumiJS example',
      description: 'ASCII art generated by SumiJS',
      background: 'transparent',
    }),
    jsonSummary: {
      version: serialized.version,
      width: serialized.width,
      height: serialized.height,
      source: serialized.metadata.source,
      font: serialized.metadata.font,
    },
  }
}
